name: Build a TiddlyWiki static site and deploy to fission

on:
  workflow_dispatch:
  push:
    branches:
      - main
      # - source
      # It is highly recommended that you only run this action on push to a 
        # specific branch, eg. master or source (if on *.github.io repo)
    
jobs:
# TODO: figure out TW static generation
  fission:
    name: 🚀 Publish to Fission
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 fission publish
        uses: fission-suite/publish-action@v1
        with:
          machine_key: ${{ secrets.FISSION_KEY }}
