name: Build a TiddlyWiki static site and deploy to fission

on:
  push:
    branches:
      - main
      # - source
      # It is highly recommended that you only run this action on push to a 
        # specific branch, eg. master or source (if on *.github.io repo)
    
jobs:
# TODO: figure out TW static generation
  fission:
    runs-on: ubuntu-latest # can change this to ubuntu-latest if you prefer
    steps:
      - name: 🚀 fission publish
        uses: fission-suite/publish-action@v1
        with:
            machine_key: ${{ secrets.FISSION_KEY }}
